# Generated by Django 3.1.5 on 2021-01-14 09:45

import _socket
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.file')),
                ('path', models.TextField(help_text='File path address to the HDF5 file.')),
                ('hostname', models.TextField(default=_socket.gethostname, help_text='Name of the (remote) host of the file.')),
            ],
            options={
                'unique_together': {('path', 'hostname')},
            },
            bases=('files.file',),
        ),
    ]
