# Generated by Django 3.1.5 on 2021-01-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_datfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFunction',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='files.file')),
                ('module_name', models.TextField(help_text="Python module import name (using '.')")),
                ('function_name', models.TextField(help_text='Name of the function inside the module.')),
                ('version', models.TextField(blank=True, help_text='Tag defining the version of the function used. Not yet used on import', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('files.file',),
        ),
    ]
