# Generated by Django 3.1.5 on 2021-01-21 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('convolutions', '0001_initial'), ('convolutions', '0002_auto_20210114_1447'), ('convolutions', '0003_auto_20210114_1505')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operators', '0001_initial'),
        ('operators', '0007_auto_20210114_1505'),
        ('densities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentConvolution',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=200, null=True)),
                ('q', models.DecimalField(decimal_places=5, help_text='Momentum transfer from operator to density.', max_digits=8)),
                ('angle', models.DecimalField(decimal_places=2, help_text='Scattering angle of initial to final scattering momentum in degerees.', max_digits=5)),
                ('mj_tot_i_x2', models.IntegerField(blank=True, help_text='Incoming total spin polarization of nucleus.', null=True)),
                ('mj_tot_o_x2', models.IntegerField(blank=True, help_text='Outgoing total spin polarization of nucleus.', null=True)),
                ('value', models.FloatField(help_text='Value of the matrix element.')),
                ('date', models.DateTimeField(auto_now=True, help_text='Date last modified.')),
                ('density', models.ForeignKey(help_text='Density used in computation.', on_delete=django.db.models.deletion.CASCADE, to='densities.density')),
                ('operator', models.ForeignKey(help_text='Operator used in computation.', on_delete=django.db.models.deletion.CASCADE, to='operators.operatorpwd')),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Anonymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('operator', 'density', 'q', 'angle', 'mj_tot_i_x2', 'mj_tot_o_x2')},
            },
        ),
    ]
