# Generated by Django 3.1.5 on 2021-01-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convolutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentconvolution',
            name='angle',
            field=models.DecimalField(decimal_places=2, help_text='Scattering angle of initial to final scattering momentum in degerees.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='currentconvolution',
            name='q',
            field=models.DecimalField(decimal_places=5, help_text='Momentum transfer from operator to density.', max_digits=8),
        ),
    ]
