# Generated by Django 3.1.5 on 2021-01-14 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0007_auto_20210114_1505'),
        ('convolutions', '0002_auto_20210114_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentconvolution',
            name='operator',
            field=models.ForeignKey(help_text='Operator used in computation.', on_delete=django.db.models.deletion.CASCADE, to='operators.operatorpwd'),
        ),
    ]
