# Generated by Django 3.1.5 on 2021-01-21 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import numpwdata.utils.encoders
import numpwdata.utils.fields


class Migration(migrations.Migration):

    replaces = [('operators', '0001_initial'), ('operators', '0002_auto_20210114_0948'), ('operators', '0003_auto_20210114_1119'), ('operators', '0004_auto_20210114_1447'), ('operators', '0005_remove_operator2npwd_qvals'), ('operators', '0006_operator2npwd_mesh_info'), ('operators', '0007_auto_20210114_1505'), ('operators', '0008_auto_20210115_0915')]

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('files', '0002_datfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0003_modulefunction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Anonymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operator2N',
            fields=[
                ('operator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operators.operator')),
                ('name', models.CharField(help_text='Name of the operator.', max_length=100, unique=True)),
                ('equation', numpwdata.utils.fields.SympyField(blank=True, encoder='expression', help_text='Describes the operator as a function of in- and outgoing nucleon momenta and Pauli spin and isospin matrices as well as external current information.', null=True, unique=True)),
                ('legend', models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='A dictinoary explaining the definitions.', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('operators.operator',),
        ),
        migrations.CreateModel(
            name='OperatorPWD',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Anonymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operator2NPWD',
            fields=[
                ('args', models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='Information about the operator arguments', null=True)),
                ('misc', models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='Miscellaneous information about the operator like quantum channels.', null=True)),
                ('file', models.OneToOneField(help_text='File information about operator.', on_delete=django.db.models.deletion.CASCADE, to='files.h5file')),
                ('operator', models.ForeignKey(help_text='Expression which identifies the operator.', on_delete=django.db.models.deletion.CASCADE, to='operators.operator2n')),
                ('mesh_info', models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='Information about the operator integration meshes.', null=True)),
                ('operatorpwd_ptr', models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operators.operatorpwd')),
            ],
            options={
                'unique_together': {('operator', 'file')},
            },
        ),
        migrations.CreateModel(
            name='Operator1N',
            fields=[
                ('operator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operators.operator')),
                ('name', models.CharField(help_text='Name of the operator.', max_length=100, unique=True)),
                ('equation', numpwdata.utils.fields.SympyField(blank=True, encoder='expression', help_text='Describes the operator as a function of in- and outgoing nucleon momenta and Pauli spin and isospin matrices as well as external current information.', null=True, unique=True)),
                ('legend', models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='A dictinoary explaining the definitions.', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('operators.operator',),
        ),
        migrations.CreateModel(
            name='Operator1NPWD',
            fields=[
                ('operatorpwd_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operators.operatorpwd')),
                ('misc', models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='Miscellaneous information about the operator like quantum channels.', null=True)),
                ('function', models.OneToOneField(help_text='Python module function implementing the PWD.', on_delete=django.db.models.deletion.CASCADE, to='files.modulefunction')),
                ('operator', models.ForeignKey(help_text='Expression which identifies the operator.', on_delete=django.db.models.deletion.CASCADE, to='operators.operator1n')),
            ],
            options={
                'unique_together': {('operator', 'function')},
            },
            bases=('operators.operatorpwd',),
        ),
    ]
