# Generated by Django 3.1.5 on 2021-01-14 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import numpwdata.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Anonymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operator1N',
            fields=[
                ('operator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operators.operator')),
                ('name', models.CharField(help_text='Name of the operator.', max_length=100)),
                ('equation', numpwdata.utils.fields.SympyField(blank=True, encoder='expression', help_text='Describes the operator as a function of in- and outgoing nucleon momenta and Pauli spin and isospin matrices as well as external current information.', null=True)),
                ('legend', models.JSONField(help_text='A dictinoary explaining the definitions.')),
            ],
            options={
                'abstract': False,
            },
            bases=('operators.operator',),
        ),
        migrations.CreateModel(
            name='Operator2N',
            fields=[
                ('operator_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operators.operator')),
                ('name', models.CharField(help_text='Name of the operator.', max_length=100, unique=True)),
                ('equation', numpwdata.utils.fields.SympyField(blank=True, encoder='expression', help_text='Describes the operator as a function of in- and outgoing nucleon momenta and Pauli spin and isospin matrices as well as external current information.', null=True, unique=True)),
                ('legend', models.JSONField(help_text='A dictinoary explaining the definitions.')),
            ],
            options={
                'abstract': False,
            },
            bases=('operators.operator',),
        ),
        migrations.CreateModel(
            name='Operator2NPWD',
            fields=[
                ('id', models.AutoField(help_text='Primary key for Base class.', primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date the class was last modified')),
                ('tag', models.CharField(blank=True, help_text='User defined tag for easy searches', max_length=200, null=True)),
                ('args', models.JSONField(help_text='Information about the operator arguments')),
                ('l12_max', models.IntegerField()),
                ('s12_max', models.IntegerField()),
                ('misc', models.JSONField(help_text='Miscellaneous information about the operator like quantum channels.')),
                ('file', models.ForeignKey(help_text='File information about operator.', on_delete=django.db.models.deletion.CASCADE, to='files.h5file')),
                ('user', models.ForeignKey(blank=True, help_text='User who updated this object. Set on save by connection to database. Anonymous if not found.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(help_text='Expression which identifies the operator.', on_delete=django.db.models.deletion.CASCADE, to='operators.operator2n')),
            ],
            options={
                'unique_together': {('operator', 'file')},
            },
        ),
    ]
