# Generated by Django 3.1.5 on 2021-01-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_squashed_0008_auto_20210115_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator2npwd',
            name='operatorpwd_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operators.operatorpwd'),
        ),
    ]
