# Generated by Django 3.1.5 on 2021-01-14 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_datfile'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator2npwd',
            name='qvals',
            field=models.JSONField(default={}, help_text='Information about the external current momentum exchange range.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operator2npwd',
            name='file',
            field=models.OneToOneField(help_text='File information about operator.', on_delete=django.db.models.deletion.CASCADE, to='files.h5file'),
        ),
    ]
