# Generated by Django 3.2.4 on 2021-06-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_auto_20210121_1500'),
        ('operators', '0002_auto_20210526_1041'),
    ]

    operations = [
    ]
