# Generated by Django 3.1.5 on 2021-01-14 14:52

from django.db import migrations, models
import numpwdata.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0005_remove_operator2npwd_qvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator2npwd',
            name='mesh_info',
            field=models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='Information about the operator integration meshes.', null=True),
        ),
    ]
