# Generated by Django 3.1.5 on 2021-01-14 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("operators", "0006_operator2npwd_mesh_info"),
    ]

    operations = [
        migrations.RemoveField(model_name="operator2npwd", name="id",),
        migrations.RemoveField(model_name="operator2npwd", name="last_modified",),
        migrations.RemoveField(model_name="operator2npwd", name="tag",),
        migrations.RemoveField(model_name="operator2npwd", name="user",),
        migrations.CreateModel(
            name="OperatorPWD",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Primary key for Base class.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        auto_now=True, help_text="Date the class was last modified"
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        help_text="User defined tag for easy searches",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who updated this object. Set on save by connection to database. Anonymous if not found.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="operator2npwd",
            name="operatorpwd_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="operators.operatorpwd",
            ),
            preserve_default=False,
        ),
    ]
