# Generated by Django 3.1.5 on 2021-01-15 09:15

from django.db import migrations, models
import django.db.models.deletion
import numpwdata.utils.encoders
import numpwdata.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_modulefunction'),
        ('operators', '0007_auto_20210114_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator1n',
            name='equation',
            field=numpwdata.utils.fields.SympyField(blank=True, encoder='expression', help_text='Describes the operator as a function of in- and outgoing nucleon momenta and Pauli spin and isospin matrices as well as external current information.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operator1n',
            name='name',
            field=models.CharField(help_text='Name of the operator.', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Operator1NPWD',
            fields=[
                ('operatorpwd_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operators.operatorpwd')),
                ('misc', models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='Miscellaneous information about the operator like quantum channels.', null=True)),
                ('function', models.OneToOneField(help_text='Python module function implementing the PWD.', on_delete=django.db.models.deletion.CASCADE, to='files.modulefunction')),
                ('operator', models.ForeignKey(help_text='Expression which identifies the operator.', on_delete=django.db.models.deletion.CASCADE, to='operators.operator1n')),
            ],
            options={
                'unique_together': {('operator', 'function')},
            },
            bases=('operators.operatorpwd',),
        ),
    ]
