# Generated by Django 3.1.5 on 2021-01-14 11:19

from django.db import migrations, models
import numpwdata.utils.encoders


class Migration(migrations.Migration):

    dependencies = [
        ('densities', '0002_auto_20210114_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiral',
            name='misc',
            field=models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='Miscellaneous information about the interaction.', null=True),
        ),
        migrations.AlterField(
            model_name='density1n',
            name='channel_info',
            field=models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='Information about quantum channels.', null=True),
        ),
        migrations.AlterField(
            model_name='density1n',
            name='mesh_info',
            field=models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='Internal mesh information used to obtain the density, e.g., in integrations.', null=True),
        ),
        migrations.AlterField(
            model_name='density1n',
            name='momentum_info',
            field=models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='Momentum mesh used for density representing the matrix.', null=True),
        ),
        migrations.AlterField(
            model_name='density2n',
            name='channel_info',
            field=models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='Information about quantum channels.', null=True),
        ),
        migrations.AlterField(
            model_name='density2n',
            name='mesh_info',
            field=models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='Internal mesh information used to obtain the density', null=True),
        ),
        migrations.AlterField(
            model_name='density2n',
            name='momentum_info',
            field=models.JSONField(blank=True, encoder=numpwdata.utils.encoders.NympyEncoder, help_text='Momentum mesh used for density representing the matrix.', null=True),
        ),
        migrations.AlterField(
            model_name='phenemenological',
            name='misc',
            field=models.JSONField(encoder=numpwdata.utils.encoders.NympyEncoder, help_text='Miscellaneous information about the interaction.'),
        ),
    ]
