# Generated by Django 3.1.5 on 2021-01-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('densities', '0003_auto_20210114_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chiral',
            name='name',
            field=models.CharField(help_text='Name of the interaction.', max_length=200),
        ),
    ]
