# Generated by Django 3.1.5 on 2021-01-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('densities', '0004_auto_20210114_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='density1n',
            name='qval',
            field=models.DecimalField(decimal_places=5, help_text='Value of momentum transfer in inverse fermi.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='density1n',
            name='thetaval',
            field=models.DecimalField(decimal_places=2, help_text='?', max_digits=5),
        ),
        migrations.AlterField(
            model_name='density2n',
            name='qval',
            field=models.DecimalField(decimal_places=5, help_text='Value of momentum transfer in inverse fermi.', max_digits=8),
        ),
        migrations.AlterField(
            model_name='density2n',
            name='thetaval',
            field=models.DecimalField(decimal_places=2, help_text='?', max_digits=5),
        ),
    ]
